version: "3"

services:
    service1:
        image: quintor/streamingtest
        ports:
          - 8081:8080
        environment:
          - service.name=ProducerService
          - kafka.bootstrapAddress=kafka:9092
          - kafka.role=producer
        depends_on:
          - kafka

    service2:
      image: quintor/streamingtest
      ports:
        - 8082:8080
      environment:
        - service.name=ProducerService
        - kafka.bootstrapAddress=kafka:9092
        - kafka.role=producer
      depends_on:
        - kafka

    service3:
      image: quintor/streamingtest
      ports:
        - 8083:8080
      environment:
        - service.name=ProducerService
        - kafka.bootstrapAddress=kafka:9092
        - kafka.role=producer
      depends_on:
        - kafka

#    serviceConsumer:
#      image: quintor/streamingtest
#      ports:
#        - 8082:8080
#      environment:
#        - service.name=ConsumerService
#        - kafka.bootstrapAddress=kafka:9092
#        - kafka.role=consumer
#      depends_on:
#        - kafka

    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

    kafka:
      image: kafkadocker_kafka
      ports:
        - "9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 10.40.121.169
        KAFKA_ADVERTISED_HOST_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "ProofOfConcept:3:1"
      depends_on:
        - zookeeper
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock